name: Catch API Data

on: [workflow_dispatch]

jobs:
  get-api-data:
    runs-on: ubuntu-latest
    steps:
      - name: Call API with curl
        id: callapi
        run: |
          response=$(curl -s https://api.github.com/repos/actions/runner/releases/latest)
          version=$(echo "$response" | jq -r '.tag_name')
          echo "Tag version $version"
          response2=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest)
          version=$(echo "$response2" | jq -r '.tag_name')
          echo "Tag version $version"